name: Build and Push Docker Image
on:
  push:
    branches:
      - main
 workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t israeladinebo/devops-node-app:latest .

      - name: Push Docker image
        run: |
          docker push israeladinebo/devops-node-app:latest

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY_B64 }}" | base64 --decode > deploy_key
          chmod 600 deploy_key

      - name: Verify SSH key
        run: |
          test -s deploy_key
          ssh-keygen -y -f deploy_key > /dev/null
          echo "SSH private key is valid"

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key_path: ./deploy_key
          script: |
            cd ~/devops-project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
